# Generated by Django 2.0.2 on 2018-02-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the descriptive course title', max_length=200)),
                ('number', models.CharField(help_text="Enter the course's title number (220 in COMPSCI 220)", max_length=6)),
                ('description', models.TextField(help_text='Enter the course description', max_length=1000)),
                ('reqs', models.TextField(help_text='Enter the course requirements', max_length=1000)),
                ('credits', models.IntegerField(help_text='Enter # of credits')),
                ('honors', models.BooleanField(verbose_name='Enter whether this class is an honors course')),
                ('open', models.BooleanField(verbose_name='Enter whether this class is currently open')),
                ('career', models.CharField(blank=True, choices=[('u', 'Undergrad'), ('g', 'Graduate'), ('c', 'Non-Credit'), ('d', 'Non-Degree')], default='u', help_text='The course career', max_length=1)),
                ('session', models.CharField(blank=True, choices=[('un', 'University'), ('uc', 'University Eligible/CPE'), ('ud', 'University Non-standard Dates'), ('c1', 'CPE Summer Session 1'), ('c2', 'CPE Summer Session 2'), ('c3', 'CPE Summer Session 3')], default='u', help_text='The course career', max_length=2)),
                ('start_date', models.DateField(help_text='Enter the starting date of the course')),
                ('end_date', models.DateField(help_text='Enter the ending date of the course')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a department name', max_length=200)),
                ('code', models.CharField(help_text='Enter the department abbreviation', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Gened',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a gened category', max_length=200)),
                ('code', models.CharField(help_text='Enter the gened abbreviation', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('w', 'Winter'), ('t', 'Summer'), ('s', 'Spring'), ('f', 'Fall')], max_length=1)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='dept',
            field=models.ForeignKey(help_text="Enter the course's department", on_delete='CASCADE', to='schedule.Department'),
        ),
        migrations.AddField(
            model_name='class',
            name='gened',
            field=models.ManyToManyField(help_text='Enter any gened categories this course satisfies', to='schedule.Gened'),
        ),
    ]
