# Generated by Django 2.0.2 on 2018-02-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='User-set title for this schedule', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('w', 'Wishlist'), ('a', 'Active')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.IntegerField(help_text='The 5 digit spire course number', primary_key=True, serialize=False)),
                ('days', models.CharField(help_text='Days the course is taught', max_length=10)),
                ('start', models.TimeField(help_text='The starting time of the class')),
                ('ending', models.TimeField(help_text='The ending time of the class')),
                ('link', models.CharField(help_text='Link to the spire page for the course', max_length=100)),
                ('professor', models.CharField(max_length=200)),
                ('room', models.CharField(max_length=200)),
                ('cap', models.IntegerField(help_text='The class maximum capacity')),
                ('enrolled', models.IntegerField(help_text='The current number of students enrolled')),
                ('wcap', models.IntegerField(help_text='The maximum size of the waitlist')),
                ('wenrolled', models.IntegerField(help_text='The current size of the waitlist')),
                ('component', models.CharField(choices=[('col', 'Colloquium'), ('dis', 'Discussion'), ('the', 'Dissertation / Thesis'), ('stu', 'Individualized Study'), ('lab', 'Laboratory'), ('lec', 'Lecture'), ('pra', 'Practicum'), ('sem', 'Seminar'), ('ski', 'Studio / Skills')], max_length=3)),
                ('clss', models.ForeignKey(help_text='The corresponding generic class for this section', on_delete='CASCADE', to='schedule.Class')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=16)),
                ('sid', models.CharField(help_text='8 digit spire id', max_length=8)),
                ('password', models.CharField(max_length=20)),
                ('credits', models.IntegerField(help_text='The current cumulative number of credits taken')),
                ('courses', models.ManyToManyField(help_text='The previous courses taken by the user', to='schedule.Section')),
                ('major', models.ForeignKey(null=True, on_delete='SET_NULL', to='schedule.Department')),
            ],
        ),
        migrations.AddField(
            model_name='scheduleclass',
            name='course',
            field=models.ForeignKey(on_delete='CASCADE', to='schedule.Section'),
        ),
        migrations.AddField(
            model_name='scheduleclass',
            name='schedule',
            field=models.ForeignKey(on_delete='CASCADE', to='schedule.Schedule'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(help_text='The user this schedule belongs to', on_delete='CASCADE', to='schedule.User'),
        ),
    ]
