# Generated by Django 2.0.2 on 2018-02-27 22:58

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('schedule', '0003_auto_20180227_1742'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Class',
        ),
        migrations.RenameModel(
            old_name='ScheduleCourse',
            new_name='ScheduleClass',
        ),
    ]
