# Generated by Django 2.0.2 on 2018-02-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20180227_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='term',
            field=models.ForeignKey(default=1, on_delete='CASCADE', to='schedule.Term'),
        ),
    ]
