# Generated by Django 2.0.2 on 2018-03-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20180323_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, help_text='Enter a department name', max_length=200, unique=True),
        ),
    ]
