# Generated by Django 2.0.2 on 2018-03-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20180323_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='open',
        ),
        migrations.AddField(
            model_name='section',
            name='open',
            field=models.BooleanField(default=True, verbose_name='Enter whether this class is currently open'),
        ),
    ]
