# Generated by Django 2.0.2 on 2018-04-07 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20180329_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='dept',
            field=models.ForeignKey(help_text="Enter the course's department", on_delete=django.db.models.deletion.CASCADE, to='schedule.Department'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(help_text='The user this schedule belongs to', on_delete=django.db.models.deletion.CASCADE, to='schedule.User'),
        ),
        migrations.AlterField(
            model_name='schedulecourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Section'),
        ),
        migrations.AlterField(
            model_name='schedulecourse',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Schedule'),
        ),
        migrations.AlterField(
            model_name='section',
            name='clss',
            field=models.ForeignKey(help_text='The corresponding generic class for this section', on_delete=django.db.models.deletion.CASCADE, to='schedule.Course'),
        ),
        migrations.AlterField(
            model_name='section',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.Term'),
        ),
    ]
