# Generated by Django 2.0.2 on 2018-04-07 21:53

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('schedule', '0011_auto_20180407_1606'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Student',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='user',
            new_name='student',
        ),
    ]
