# Generated by Django 2.0.2 on 2018-04-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_auto_20180407_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulecourse',
            name='color',
            field=models.CharField(default='#157ddf9f', help_text='Enter the color for this course', max_length=15),
        ),
    ]
