# Generated by Django 2.0.2 on 2018-04-10 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_auto_20180409_1433'),
        ('schedule', '0014_auto_20180409_1028'),
    ]

    operations = [
    ]
