# Generated by Django 2.0.2 on 2018-04-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_merge_20180410_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='password', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
