# Generated by Django 2.0.2 on 2018-04-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_auto_20180410_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(help_text='Your username', max_length=30),
        ),
    ]
