# Generated by Django 2.0.2 on 2018-04-10 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_auto_20180410_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
