# Generated by Django 2.0.2 on 2018-04-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_remove_student_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Your username', max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('sid', models.CharField(help_text='8 digit spire id', max_length=8)),
                ('credits', models.IntegerField(help_text='The current cumulative number of credits taken')),
                ('major', models.ForeignKey(null=True, on_delete='SET_NULL', to='schedule.Department')),
            ],
        ),
    ]
