# Generated by Django 2.0.2 on 2018-04-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0022_auto_20180410_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
