# Generated by Django 2.0.2 on 2018-04-10 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0023_student_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
