# Generated by Django 2.0.2 on 2018-04-10 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0024_remove_student_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sid',
        ),
    ]
