# Generated by Django 2.0.2 on 2018-04-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0027_auto_20180410_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='sid',
            field=models.CharField(help_text='8 digit spire id', max_length=8, primary_key=True, serialize=False),
        ),
    ]
