# Generated by Django 2.0.2 on 2018-04-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0027_auto_20180413_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='component',
            field=models.CharField(choices=[('LEC', 'Lecture'), ('DIS', 'Discussion'), ('LAB', 'Laboratory'), ('COL', 'Colloquium'), ('DST', 'Dissertation / Thesis'), ('IND', 'Individualized Study'), ('PRA', 'Practicum'), ('SEM', 'Seminar'), ('STS', 'Studio / Skills')], max_length=3),
        ),
    ]
