# Generated by Django 2.0.2 on 2018-04-18 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0028_auto_20180418_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='link',
        ),
    ]
