# Generated by Django 2.0.2 on 2018-04-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0029_auto_20180410_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='student',
        ),
    ]
