# Generated by Django 2.0.2 on 2018-04-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0029_remove_section_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='mon',
            field=models.BooleanField(default=False),
        ),
    ]
