# Generated by Django 2.0.2 on 2018-04-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0030_section_mon'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='fri',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='thu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='tue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='wed',
            field=models.BooleanField(default=False),
        ),
    ]
