# Generated by Django 2.0.2 on 2018-04-23 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0031_auto_20180419_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='clss',
            field=models.ForeignKey(blank=True, help_text='The corresponding generic class for this section', null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Course'),
        ),
        migrations.AlterField(
            model_name='section',
            name='component',
            field=models.CharField(choices=[('LEC', 'Lecture'), ('DIS', 'Discussion'), ('LAB', 'Laboratory'), ('COL', 'Colloquium'), ('DST', 'Dissertation / Thesis'), ('IND', 'Individualized Study'), ('PRA', 'Practicum'), ('SEM', 'Seminar'), ('STS', 'Studio / Skills'), ('CUS', 'Custom')], max_length=3),
        ),
    ]
