# Generated by Django 2.0.2 on 2018-04-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0031_auto_20180410_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='The previous courses taken by the user', to='schedule.Section'),
        ),
        migrations.AddField(
            model_name='student',
            name='credits',
            field=models.IntegerField(help_text='The current cumulative number of credits taken', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.ForeignKey(null=True, on_delete='SET_NULL', to='schedule.Department'),
        ),
        migrations.AddField(
            model_name='student',
            name='sid',
            field=models.CharField(help_text='8 digit spire id', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
