# Generated by Django 2.0.2 on 2018-04-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0032_auto_20180410_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='credits',
            field=models.IntegerField(help_text='The current cumulative number of credits taken'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sid',
            field=models.CharField(help_text='8 digit spire id', max_length=8),
        ),
    ]
