# Generated by Django 2.0.2 on 2018-04-10 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0034_studentmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentManager',
        ),
    ]
