# Generated by Django 2.0.2 on 2018-04-23 13:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0034_section_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
