# Generated by Django 2.0.2 on 2018-04-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0035_delete_studentmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.CharField(help_text='Enter # of credits', max_length=3),
        ),
    ]
