# Generated by Django 2.0.2 on 2018-04-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0035_auto_20180423_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='sid',
            field=models.IntegerField(blank=True, help_text='The 5 digit spire course number', null=True),
        ),
    ]
