# Generated by Django 2.0.2 on 2018-04-23 15:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0037_auto_20180423_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
