# Generated by Django 2.0.2 on 2018-04-23 15:57

from django.db import migrations, models
from schedule.models import Section
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0038_auto_20180423_1157'),
    ]

    def gen_uuid(apps, schema_editor):
        for row in Section.objects.all():
            row.uid = uuid.uuid4()
            row.save()
    
    operations = [
        migrations.RunPython(gen_uuid),
        migrations.AlterField(
            model_name='section',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
