# Generated by Django 2.0.2 on 2018-04-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0039_auto_20180423_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulecourse',
            name='course',
        ),
    ]
