# Generated by Django 2.0.2 on 2018-04-23 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0040_remove_schedulecourse_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulecourse',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Section'),
        ),
    ]
