# Generated by Django 2.0.2 on 2018-04-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0043_remove_student_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulecourse',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('#157ddf9f', 'blue'), ('blammo', 'green'), ('orange', 'orange'), ('purple', 'purple'), ('pink', 'pink'), ('brown', 'brown')], default='blue', help_text='Enter the color for this course', max_length=15),
        ),
    ]
