# Generated by Django 2.0.2 on 2018-04-25 15:48

from django.db import migrations, models
import schedule.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0045_auto_20180425_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='student',
            name='major',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sid',
        ),
        migrations.AlterField(
            model_name='schedulecourse',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('#157ddf9f', 'blue'), ('green', 'green'), ('orange', 'orange'), ('purple', 'purple'), ('pink', 'pink'), ('brown', 'brown')], default=schedule.models.get_color, help_text='Enter the color for this course', max_length=15),
        ),
    ]
