# Generated by Django 2.0.2 on 2018-04-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0046_auto_20180425_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.CharField(help_text='Enter # of credits', max_length=4),
        ),
    ]
